using Application.Interfaces;
using Application.Services;
using Infrastructure.Data;
using Infrastructure.Services;
using Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Application.Mappings;
using FluentValidation;
using Application.Validators;
using FluentValidation.AspNetCore;
using Microsoft.IdentityModel.Tokens;
using Application.DTOs;

var builder = WebApplication.CreateBuilder(args);

//DB
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

//JWT authentication
builder.Services.AddAuthentication("Bearer")
    .AddJwtBearer("Bearer", options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = false,
            ValidateAudience = false,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey
                                (System.Text.Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]
                                ?? throw new ArgumentNullException("Jwt:Key configuration is missing.")))
        };
    });

builder.Services.Configure<TokenSettings>(
builder.Configuration.GetSection("Jwt"));

builder.Services.AddHttpContextAccessor();

//register services
// The registration of IGuidService with different lifetimes (Transient, Scoped, Singleton) will affect how the GUID values are generated and returned in the TestController. Depending on the chosen lifetime, the behavior of _guidService1 and _guidService2 will differ, demonstrating the impact of service lifetimes on the state and behavior of services in an ASP.NET Core application.
//builder.Services.AddTransient<IGuidService, GuidService>(); // Transient: A new instance of GuidService will be created each time it is requested. This means that _guidService1 and _guidService2 will have different GUID values every time the Get method is called.
//builder.Services.AddScoped<IGuidService, GuidService>(); // Scoped: A new instance of GuidService will be created for each HTTP request. Within the same request, _guidService1 and _guidService2 will return the same GUID value, but across different requests, they will return different GUID values.
// builder.Services.AddSingleton<IGuidService, GuidService>(); // Singleton: A single instance of GuidService will be created and shared across the entire application. This means that _guidService1 and _guidService2 will always return the same GUID value, regardless of the request or how many times the Get method is called.
builder.Services.AddScoped<IGuidService, GuidService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IPasswordHasher, PasswordHasher>();
builder.Services.AddScoped<ITokenService, TokenService>();
builder.Services.AddTransient<IDataService, DateService>();
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<ICurrentUserService, CurrentUserService>();
builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();

//register repositories
builder.Services.AddScoped<IUserRepository, UserRepository>();
builder.Services.AddScoped<ITokenRepository, TokenRepository>();


//Mappers
builder.Services.AddAutoMapper(typeof(MappingProfile));

builder.Services.AddControllers();

//validation
builder.Services.AddValidatorsFromAssemblyContaining<CreateUserValidator>();

builder.Services.AddFluentValidationAutoValidation();

//for swagger
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend",
        policy =>
        {
            policy.WithOrigins("http://localhost:5173")
                  .AllowAnyHeader()
                  .AllowAnyMethod()
                  .AllowCredentials();
        });
});

var app = builder.Build();
app.UseCors("AllowFrontend");

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapControllers();

// Add custom middleware to the request pipeline
// The order of middleware is important. LearnMiddleware will execute before LoggingMiddleware, allowing you to see the effects of LearnMiddleware in the logs generated by LoggingMiddleware.
app.UseMiddleware<LearnMiddleware>();
app.UseMiddleware<LoggingMiddleware>();

app.UseAuthentication();
app.UseAuthorization();

app.Run();